In [1]:
!pip install langchain

Collecting langchain
  Downloading langchain-1.3.1-py3-none-any.whl.metadata (5.8 kB)
Collecting langchain-core<2.0.0,>=1.4.0 (from langchain)
  Downloading langchain_core-1.4.0-py3-none-any.whl.metadata (4.5 kB)
Collecting langgraph<1.3.0,>=1.2.0 (from langchain)
  Downloading langgraph-1.2.0-py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain) (2.10.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)
Collecting langchain-protocol>=0.0.14 (from langchain-core<2.0.0,>=1.4.0->langchain)
  Downloading langchain_protocol-0.0.15-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.4.0->langchain)
  Downloading langsmith-0.8.5-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging>=23.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.0.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.4.0->langchain)
  Downloading uuid_utils-0.16.0-cp313-cp313-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (2.1)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph<1.3.0,>=1.2.0->langchain)
  Downloading langgraph_checkpoint-4.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph<1.3.0,>=1.2.0->langchain)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.4.0,>=0.3.0 (from langgraph<1.3.0,>=1.2.0->langchain)
  Downloading langgraph_sdk-0.3.14-py3-none-any.whl.metadata (1.7 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.3.0,>=1.2.0->langchain)
  Downloading xxhash-3.7.0-cp313-cp313-win_amd64.whl.metadata (13 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.0->langchain)
  Downloading ormsgpack-1.12.2-cp313-cp313-win_amd64.whl.metadata (3.3 kB)
Requirement already satisfied: httpx>=0.25.2 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (0.28.1)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain)
  Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.3)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.23.0)
Requirement already satisfied: anyio in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (4.7.0)
Requirement already satisfied: certifi in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\lenovo\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.27.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (1.3.0)
Downloading langchain-1.3.1-py3-none-any.whl (114 kB)
Downloading langchain_core-1.4.0-py3-none-any.whl (548 kB)
   ---------------------------------------- 0.0/548.1 kB ? eta -:--:--
   --------------------------------------- 548.1/548.1 kB 11.1 MB/s eta 0:00:00
Downloading langgraph-1.2.0-py3-none-any.whl (234 kB)
Downloading langgraph_checkpoint-4.1.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.3.14-py3-none-any.whl (97 kB)
Downloading langsmith-0.8.5-py3-none-any.whl (399 kB)
Downloading uuid_utils-0.16.0-cp313-cp313-win_amd64.whl (174 kB)
Downloading langchain_protocol-0.0.15-py3-none-any.whl (7.0 kB)
Downloading orjson-3.11.9-cp313-cp313-win_amd64.whl (127 kB)
Downloading ormsgpack-1.12.2-cp313-cp313-win_amd64.whl (117 kB)
Downloading xxhash-3.7.0-cp313-cp313-win_amd64.whl (31 kB)
Installing collected packages: xxhash, uuid-utils, ormsgpack, orjson, langchain-protocol, langsmith, langgraph-sdk, langchain-core, langgraph-checkpoint, langgraph-prebuilt, langgraph, langchain

  Attempting uninstall: orjson

    Found existing installation: orjson 3.11.4

    Uninstalling orjson-3.11.4:

      Successfully uninstalled orjson-3.11.4

   ---------------- -----------------------  5/12 [langsmith]
   ---------------- -----------------------  5/12 [langsmith]
   ---------------- -----------------------  5/12 [langsmith]
   -------------------- -------------------  6/12 [langgraph-sdk]
   ----------------------- ----------------  7/12 [langchain-core]
   ----------------------- ----------------  7/12 [langchain-core]
   ----------------------- ----------------  7/12 [langchain-core]
   ----------------------- ----------------  7/12 [langchain-core]
   ----------------------- ----------------  7/12 [langchain-core]
   -------------------------- -------------  8/12 [langgraph-checkpoint]
   --------------------------------- ------ 10/12 [langgraph]
   --------------------------------- ------ 10/12 [langgraph]
   ------------------------------------ --- 11/12 [langchain]
   ---------------------------------------- 12/12 [langchain]

Successfully installed langchain-1.3.1 langchain-core-1.4.0 langchain-protocol-0.0.15 langgraph-1.2.0 langgraph-checkpoint-4.1.0 langgraph-prebuilt-1.1.0 langgraph-sdk-0.3.14 langsmith-0.8.5 orjson-3.11.9 ormsgpack-1.12.2 uuid-utils-0.16.0 xxhash-3.7.0

In [4]:
!pip install langchain langchain-community langchain-text-splitters

Requirement already satisfied: langchain in c:\users\lenovo\anaconda3\lib\site-packages (1.3.1)
Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-text-splitters
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain) (1.4.0)
Requirement already satisfied: langgraph<1.3.0,>=1.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain) (1.2.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain) (2.10.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.14 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.0.15)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.8.5)
Requirement already satisfied: packaging>=23.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (6.0.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (9.0.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-core<2.0.0,>=1.4.0->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\lenovo\anaconda3\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.0->langchain) (2.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph<1.3.0,>=1.2.0->langchain) (4.1.0)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph<1.3.0,>=1.2.0->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph<1.3.0,>=1.2.0->langchain) (0.3.14)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph<1.3.0,>=1.2.0->langchain) (3.7.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.0->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in c:\users\lenovo\anaconda3\lib\site-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.32.3)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (0.23.0)
Requirement already satisfied: anyio in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (4.7.0)
Requirement already satisfied: certifi in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\lenovo\anaconda3\lib\site-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\lenovo\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.27.1)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.7-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-community) (2.0.39)
Collecting requests>=2.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-community) (3.11.10)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting pydantic-settings<3.0.0,>=2.10.1 (from langchain-community)
  Downloading pydantic_settings-2.14.1-py3-none-any.whl.metadata (3.4 kB)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: numpy>=2.1.0 in c:\users\lenovo\anaconda3\lib\site-packages (from langchain-community) (2.1.3)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\lenovo\anaconda3\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.18.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\lenovo\anaconda3\lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.1.0)
Collecting typing-inspection>=0.4.0 (from pydantic-settings<3.0.0,>=2.10.1->langchain-community)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\lenovo\anaconda3\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.0->langchain) (2.5.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\lenovo\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\lenovo\anaconda3\lib\site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.3.0,>=1.2.0->langchain) (1.3.0)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ---------------------------------------- 0.0/2.5 MB ? eta -:--:--
   ---------------- ----------------------- 1.0/2.5 MB 7.4 MB/s eta 0:00:01
   ---------------------------------------- 2.5/2.5 MB 6.4 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.7-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 1.0/1.0 MB 8.1 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.2-py3-none-any.whl (35 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
Downloading pydantic_settings-2.14.1-py3-none-any.whl (60 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: typing-inspection, typing-inspect, requests, marshmallow, httpx-sse, dataclasses-json, pydantic-settings, langchain-text-splitters, langchain-classic, langchain-community

  Attempting uninstall: requests

    Found existing installation: requests 2.32.3

    Uninstalling requests-2.32.3:

      Successfully uninstalled requests-2.32.3

   ------------ ---------------------------  3/10 [marshmallow]
  Attempting uninstall: pydantic-settings
   ------------ ---------------------------  3/10 [marshmallow]
    Found existing installation: pydantic-settings 2.6.1
   ------------ ---------------------------  3/10 [marshmallow]
   ------------------------ ---------------  6/10 [pydantic-settings]
    Uninstalling pydantic-settings-2.6.1:
   ------------------------ ---------------  6/10 [pydantic-settings]
      Successfully uninstalled pydantic-settings-2.6.1
   ------------------------ ---------------  6/10 [pydantic-settings]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   -------------------------------- -------  8/10 [langchain-classic]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ------------------------------------ ---  9/10 [langchain-community]
   ---------------------------------------- 10/10 [langchain-community]

Successfully installed dataclasses-json-0.6.7 httpx-sse-0.4.3 langchain-classic-1.0.7 langchain-community-0.4.1 langchain-text-splitters-1.1.2 marshmallow-3.26.2 pydantic-settings-2.14.1 requests-2.34.2 typing-inspect-0.9.0 typing-inspection-0.4.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires protobuf<7,>=3.20, but you have protobuf 7.34.1 which is incompatible.

In [17]:
import pandas as pd
import os

from langchain_text_splitters import RecursiveCharacterTextSplitter

In [18]:
DATA_PATH = r"D:\1 Univesrity work\Lect 2\Data semantics\Knowledge-Graph-Enhanced-RAG-System-for-Academic-Question-Answering-in-a-Data-Science-Curriculum\processed\all_subjects_text.csv"

df = pd.read_csv(DATA_PATH)

df.head()

,subject,file_name,text
0,data_management,0-CommonIntro.pdf,data management 2 teaching team 1 course goals...
1,data_management,1-DataLifeCycle.pdf,data lifecycle 2 methodologies 1 tools 2 phase...
2,data_management,11 LLM.pdf,a very general overview llm and data 1 2 large...
3,data_management,2- Data Acquisition.pdf,i need data data acquisition 1 2 data acquisit...
4,data_management,2.0- Data Acquisition.pdf,data management lab 2 data acquisition: web sc...

In [19]:
print(df.shape)

print(df.columns)

(118, 3)
Index(['subject', 'file_name', 'text'], dtype='object')

In [20]:
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=700,
    chunk_overlap=100,
    length_function=len
)

In [21]:
all_chunks = []

In [22]:
for idx, row in df.iterrows():

    text = row["text"]

    subject = row["subject"]

    file_name = row["file_name"]

    chunks = text_splitter.split_text(text)

    for chunk_id, chunk in enumerate(chunks):

        all_chunks.append({
            "subject": subject,
            "file_name": file_name,
            "chunk_id": chunk_id,
            "chunk_text": chunk
        })

In [23]:
chunks_df = pd.DataFrame(all_chunks)

print(chunks_df.shape)

chunks_df.head()

(4619, 4)

,subject,file_name,chunk_id,chunk_text
0,data_management,0-CommonIntro.pdf,0,data management 2 teaching team 1 course goals...
1,data_management,0-CommonIntro.pdf,1,"d. b. meysman, and mohamed ali. introducing da..."
2,data_management,0-CommonIntro.pdf,2,for the project the project must be approved ...
3,data_management,0-CommonIntro.pdf,3,you must present a new project spotywhy social...
4,data_management,1-DataLifeCycle.pdf,0,data lifecycle 2 methodologies 1 tools 2 phase...

In [24]:
print(chunks_df.iloc[0]["chunk_text"])

data management 2 teaching team 1 course goals and organization 2 exam rules 3 experience from the past 4 teaching team  data management  prof. andrea maurino (lead professor) andrea.maurinounimib.it schedule  see the calendar  november 25 and 26 there will be recorded lecturs  in-presence and registered lessons course organization  main topic: data life cycle  data science not only big data data management data management data visualization data visualization storytelling - machine learning and decision models - statistical modelling what a real data scientist do the truth.  davy cielen, arno d. b. meysman, and mohamed ali. introducing data science, manning, 2016  harrison next generation

In [25]:
chunks_df["chunk_length"] = chunks_df["chunk_text"].apply(len)

chunks_df["chunk_length"].describe()

count    4619.000000
mean      687.038969
std        56.591106
min       103.000000
25%       693.000000
50%       696.000000
75%       698.000000
max       700.000000
Name: chunk_length, dtype: float64

In [26]:
OUTPUT_FOLDER = r"D:\1 Univesrity work\Lect 2\Data semantics\Knowledge-Graph-Enhanced-RAG-System-for-Academic-Question-Answering-in-a-Data-Science-Curriculum\processed"

output_file = os.path.join(OUTPUT_FOLDER, "chunked_data.csv")

chunks_df.to_csv(output_file, index=False)

print("Chunked dataset saved!")

Chunked dataset saved!

In [27]:
def retrieve_chunks(query, top_k=5):

    query_embedding = embedding_model.encode([query])

    distances, indices = index.search(
        np.array(query_embedding).astype("float32"),
        top_k
    )

    results = []

    for idx in indices[0]:
        results.append(chunks_df.iloc[idx]["chunk_text"])  # IMPORTANT FIX

    return results

In [28]:
def build_context(query):

    retrieved_chunks = retrieve_chunks(query)

    kg_facts = retrieve_kg_facts(query)

    context = "\n\n".join(retrieved_chunks[:3])

    if kg_facts:
        context += "\n\nKnowledge Graph Facts:\n"
        context += "\n".join(kg_facts)

    return context

In [29]:
chunks_df["chunk_text"]

0       data management 2 teaching team 1 course goals...
1       d. b. meysman, and mohamed ali. introducing da...
2       for the project  the project must be approved ...
3       you must present a new project spotywhy social...
4       data lifecycle 2 methodologies 1 tools 2 phase...
                              ...
4614    class in boosting. in 7th european conference ...
4615    beats over-sampling. in proceedings of the icm...
4616    conference on machine learning, (pp. 179186). ...
4617    conference on knowledge discovery and data min...
4618    recognition techniques for detection of microc...
Name: chunk_text, Length: 4619, dtype: object